services:
#    oc_user.example:
#        class: OC\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]



# src/OC/PlatformBundle/Resources/config/services.yml


    oc_platform.validator.antiflood:                              # Le nom du service
        class: OC\PlatformBundle\Validator\AntifloodValidator     # La classe du service, ici notre validateur déjà créé
        arguments: [@request_stack, @doctrine.orm.entity_manager] # Les données qu'on injecte au service : la requête et lEntityManager
        tags:
            - { name: validator.constraint_validator, alias: oc_platform_antiflood }  # C'est avec l'alias qu'on retrouvera le service

