services:
#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

#    oc_platform.doctrine.notification:
#        class: OC\PlatformBundle\DoctrineListener\ApplicationNotification
#        arguments: [@mailer]
#            tags:
#                - { name: doctrine.event_listener, event: postPersist}

    oc_platform.validator.antiflood:
        class: OC\PlatformBundle\validator\AntifloodValidator
        arguments: [@request_stack, @doctrine.orm.entity_manager]
        tags:
            - { name: validator:constraint_validator, alias: oc_platform_antiflood}
