services:
#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

#    oc_platform.doctrine.notification:
#        class: OC\PlatformBundle\DoctrineListener\ApplicationNotification
#        arguments: [@mailer]
#            tags:
#                - { name: doctrine.event_listener, event: postPersist}

    oc_platform.validator.antiflood:
        class: OC\PlatformBundle\validator\AntifloodValidator
        arguments: [@request_stack, @doctrine.orm.entity_manager]
        tags:
            - { name: validator:constraint_validator, alias: oc_platform_antiflood}

    oc_platform.beta.html:
        class: OC\PlatformBundle\Beta\BetaHTML

    oc_platform.beta.listener:
        class: OC\PlatformBundle\Beta\BetaListener
        arguments: [@oc_platform.beta.html,"2013-10-20"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: processBeta }

    oc_platform.json_paramconverter:
        class: OC\PlatformBundle\ParamConverter\JsonParamConverter
        tags:
            - { name: request.param_converter }
