<?php

namespace OC\UserBundle\Entity;

/**
 * UseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UseurRepository extends \Doctrine\ORM\EntityRepository
{
}
